// Auto-generated by LibreLane
module sar_ctrl_async_phys(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input rst_n,
  input track,
  input cmp_p,
  input cmp_n,
  output cmp_fire,
  output cmp_valid,
  output cmp_fault,
  output[7:0] dac_code,
  output[7:0] dac_code_n,
  output[7:0] bit_active,
  output sample,
  output hold_req,
  output busy,
  output done,
  output[7:0] result
);
endmodule
