// Auto-generated by LibreLane
module sar_ctrl(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input start,
  input cmp,
  input cmp_n,
  output clk_cmp,
  output[7:0] dac_code,
  output[7:0] dac_code_n,
  output sample,
  output hold,
  output busy,
  output done,
  output[7:0] result
);
endmodule
