#!/usr/bin/env python3
"""Derive dynamic and energy figures from an existing OA-SAR8 PEX run.

The ADC output record is taken from the metrics JSON generated by
``run_core18_pex.py``.  Supply power is integrated over the final complete
FFT record in the corresponding waveform, excluding the UIC/reset startup.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np


def rising_times(t: np.ndarray, x: np.ndarray, level: float = 0.75) -> np.ndarray:
    idx = np.flatnonzero((x[:-1] < level) & (x[1:] >= level))
    return t[idx] + (level - x[idx]) * (t[idx + 1] - t[idx]) / (x[idx + 1] - x[idx])


def falling_times(t: np.ndarray, x: np.ndarray, level: float = 0.75) -> np.ndarray:
    idx = np.flatnonzero((x[:-1] > level) & (x[1:] <= level))
    return t[idx] + (x[idx] - level) * (t[idx + 1] - t[idx]) / (x[idx] - x[idx + 1])


def folded_bin(harmonic: int, tone_bin: int, points: int) -> int:
    raw = (harmonic * tone_bin) % points
    return min(raw, points - raw)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("metrics", type=Path)
    parser.add_argument("wave", type=Path)
    parser.add_argument("--vdd", type=float, default=1.5)
    parser.add_argument("--harmonics", type=int, default=5)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    base = json.loads(args.metrics.read_text(encoding="utf-8"))
    n = int(base["fft_points"])
    k = int(base["tone_bin"])
    fs = float(base["fs_msps"]) * 1e6
    codes = np.asarray(base["codes"][-n:], dtype=float)
    centered = codes - np.mean(codes)
    spectrum = np.fft.rfft(centered)
    power = np.abs(spectrum) ** 2
    power[0] = 0.0
    signal = float(power[k])
    other_bins = [index for index in range(1, len(power)) if index != k]
    spur_bin = max(other_bins, key=lambda index: power[index])
    sfdr_db = 10.0 * math.log10(signal / float(power[spur_bin]))

    harmonic_bins: list[int] = []
    for harmonic in range(2, args.harmonics + 1):
        index = folded_bin(harmonic, k, n)
        if index not in (0, k) and index not in harmonic_bins:
            harmonic_bins.append(index)
    harmonic_power = float(sum(power[index] for index in harmonic_bins))
    thd_db = 10.0 * math.log10(harmonic_power / signal)

    header = args.wave.read_text(encoding="utf-8", errors="replace").splitlines()[0].split()
    data = np.loadtxt(args.wave, skiprows=1)
    t = data[:, 0]
    track = data[:, header.index("v(track)")]
    done = data[:, header.index("v(done)")]
    current = data[:, header.index("i(VDD)")]
    track_falls = falling_times(t, track)
    done_rises = rising_times(t, done)
    # The signoff run contains one warm-up conversion plus N FFT conversions.
    # Integrate from the second aperture through the end of the final full
    # sample period, thereby excluding the non-physical UIC current impulse.
    start = float(track_falls[-n])
    stop = min(float(t[-1]), start + n / fs)
    mask = (t >= start) & (t <= stop)
    periodic_current_a = -float(np.trapezoid(current[mask], t[mask]) / (stop - start))
    periodic_power_w = args.vdd * periodic_current_a

    # Keep a second value exactly aligned with the original repository's
    # published convention: first valid aperture through the last DONE edge.
    valid_done = done_rises[done_rises > track_falls[0]]
    baseline_start = float(track_falls[0])
    baseline_stop = float(valid_done[-1])
    baseline_mask = (t >= baseline_start) & (t <= baseline_stop)
    avg_current_a = -float(
        np.trapezoid(current[baseline_mask], t[baseline_mask])
        / (baseline_stop - baseline_start)
    )
    power_w = args.vdd * avg_current_a

    sndr_db = float(base["sndr_db"])
    enob = float(base["enob_bit"])
    walden_j = power_w / (fs * 2.0**enob)
    schreier_db = sndr_db + 10.0 * math.log10((fs / 2.0) / power_w)

    result = dict(base)
    result.update({
        "sfdr_db": sfdr_db,
        "largest_spur_bin": spur_bin,
        "thd_db_2nd_to_5th": thd_db,
        "harmonic_bins_2nd_to_5th": harmonic_bins,
        "power_window_definition": "first valid TRACK falling edge through last DONE rising edge",
        "power_window_start_s": baseline_start,
        "power_window_stop_s": baseline_stop,
        "average_vdd_current_a": avg_current_a,
        "average_power_w": power_w,
        "periodic_fft_window_start_s": start,
        "periodic_fft_window_stop_s": stop,
        "periodic_average_vdd_current_a": periodic_current_a,
        "periodic_average_power_w": periodic_power_w,
        "walden_fom_j_per_conv_step": walden_j,
        "walden_fom_fj_per_conv_step": walden_j * 1e15,
        "schreier_fom_db": schreier_db,
    })
    args.out.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
